[package]
name = "p2pool-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.53", features = ["tcp", "dns", "tokio", "noise", "yamux", "identify", "macros", "ping"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
