[package]
name = "p2pool-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.53", features = ["tcp", "dns", "tokio", "noise", "yamux", "identify", "macros", "ping", "gossipsub", "kad", "mdns", "secp256k1"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
prost = "0.13.4"

[lib]
name = "p2poolv2"
path = "src/lib.rs"

[[bin]]
name = "p2poolv2"
path = "src/main.rs"

[dev-dependencies]
tokio = { version = "1.0", features = ["full", "test-util"] }
