services:
  bitcoind:
    build:
      context: .
      dockerfile: Dockerfile.bitcoind
    volumes:
      - bitcoin_data:/data
    ports:
      - "38333:38333" # P2P port
      - "38332:38332" # RPC port
    restart: unless-stopped
  cpuminer:
    build:
      context: .
      dockerfile: Dockerfile.cpuminer
    depends_on:
      - bitcoind
      - ckpool
    restart: unless-stopped
  ckpool:
    build:
      context: .
      dockerfile: Dockerfile.ckpool-solo
    ports:
      - "3333:3333"
      - "8881:8881"
    depends_on:
      - bitcoind
    restart: unless-stopped
  p2pool:
    build:
      context: ..
      dockerfile: docker/Dockerfile.p2pool
    depends_on:
      - bitcoind
      - ckpool
    restart: unless-stopped
    
volumes:
  bitcoin_data:
