services:
  bitcoind:
    build:
      context: .
      dockerfile: Dockerfile.bitcoind
    volumes:
      - bitcoin_data:/data
    ports:
      - "38333:38333" # P2P port
      - "38332:38332" # RPC port
    restart: unless-stopped

volumes:
  bitcoin_data:
